// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebaseconfig: {
    apiKey: 'AIzaSyAtfardMI6HzE-NmAJlJ-dkOz646-vgInQ',
    authDomain: 'stemid-2c13b.firebaseapp.com',
    databaseURL: 'https://stemid-2c13b.firebaseio.com',
    projectId: 'stemid-2c13b',
    storageBucket: 'stemid-2c13b.appspot.com',
    messagingSenderId: '210602342603'
  }
};
