// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebaseconfig: {
    apiKey: 'AIzaSyAtfardMI6HzE-NmAJlJ-dkOz646-vgInQ',
    authDomain: 'stemid-2c13b.firebaseapp.com',
    databaseURL: 'https://stemid-2c13b.firebaseio.com',
    projectId: 'stemid-2c13b',
    storageBucket: 'stemid-2c13b.appspot.com',
    messagingSenderId: '210602342603'
  }
};
